"use client";

import Link from "next/link";
import { Mahasiswa } from "@/lib/types";
import EmptyState from "./empty-state";

export default function StudentTable({ data, onDelete, menghapus }: { data: Mahasiswa[]; onDelete: (mahasiswa: Mahasiswa) => void; menghapus?: string }) {
  if (!data.length) return <EmptyState judul="Mahasiswa tidak ditemukan" deskripsi="Ubah kata kunci pencarian atau tambahkan mahasiswa baru." />;
  return <div className="overflow-hidden rounded-2xl bg-white shadow-soft"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-orange-50 text-xs uppercase tracking-wide text-orange-800"><tr>{["Nama", "NIM", "Prodi", "Angkatan", "Kode Mahasiswa", "Aksi"].map((judul) => <th key={judul} className="px-5 py-4 font-semibold">{judul}</th>)}</tr></thead><tbody className="divide-y divide-stone-100">{data.map((mhs) => <tr key={mhs.id} className="hover:bg-cream/60"><td className="px-5 py-4 font-semibold text-stone-800">{mhs.nama}</td><td className="px-5 py-4 text-stone-600">{mhs.nim}</td><td className="px-5 py-4 text-stone-600">{mhs.prodi}</td><td className="px-5 py-4 text-stone-600">{mhs.angkatan}</td><td className="px-5 py-4"><code className="rounded-md bg-sunshine-100 px-2 py-1 text-xs font-semibold text-orange-800">{mhs.kode_mahasiswa}</code></td><td className="px-5 py-4"><div className="flex gap-2"><Link href={`/data-mahasiswa/${mhs.id}/qr`} className="rounded-lg bg-sunshine-100 px-2.5 py-1.5 text-xs font-semibold text-orange-800 hover:bg-sunshine-300">Lihat QR</Link><Link href={`/data-mahasiswa/${mhs.id}/edit`} className="rounded-lg bg-orange-100 px-2.5 py-1.5 text-xs font-semibold text-orange-700 hover:bg-orange-200">Edit</Link><button disabled={menghapus === mhs.id} onClick={() => onDelete(mhs)} className="rounded-lg bg-red-50 px-2.5 py-1.5 text-xs font-semibold text-red-600 hover:bg-red-100 disabled:opacity-50">{menghapus === mhs.id ? "Menghapus..." : "Hapus"}</button></div></td></tr>)}</tbody></table></div></div>;
}
