"use client";

import { useEffect, useState } from "react";
import DashboardCard from "@/components/dashboard-card";
import LoadingState from "@/components/loading-state";
import AlertMessage from "@/components/alert-message";
import { supabase } from "@/lib/supabase";
import { getTanggalHariIni } from "@/lib/utils";

export default function DashboardPage() {
  const [data, setData] = useState({ mahasiswa: 0, hariIni: 0, absensi: 0, prodi: 0 }); const [muat, setMuat] = useState(true); const [galat, setGalat] = useState("");
  useEffect(() => { async function ambil() { const [mahasiswa, hariIni, absensi, daftar] = await Promise.all([supabase.from("mahasiswa").select("id", { count: "exact", head: true }), supabase.from("absensi").select("id", { count: "exact", head: true }).eq("tanggal", getTanggalHariIni()), supabase.from("absensi").select("id", { count: "exact", head: true }), supabase.from("mahasiswa").select("prodi")]); if (mahasiswa.error || hariIni.error || absensi.error || daftar.error) setGalat("Ringkasan tidak dapat dimuat. Periksa konfigurasi Supabase dan kebijakan akses."); else setData({ mahasiswa: mahasiswa.count ?? 0, hariIni: hariIni.count ?? 0, absensi: absensi.count ?? 0, prodi: new Set(daftar.data.map((item) => item.prodi)).size }); setMuat(false); } ambil(); }, []);
  return <><header className="mb-7"><p className="text-sm font-medium text-orange-600">Selamat datang, Admin 👋</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-stone-900">Dashboard</h1><p className="mt-2 text-stone-500">Kelola data mahasiswa dan absensi dengan mudah.</p></header>{galat && <div className="mb-5"><AlertMessage jenis="galat" pesan={galat} /></div>}{muat ? <LoadingState /> : <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><DashboardCard judul="Total Mahasiswa" nilai={data.mahasiswa} keterangan="Mahasiswa yang terdaftar" ikon="♙" /><DashboardCard judul="Hadir Hari Ini" nilai={data.hariIni} keterangan="Absensi pada hari ini" ikon="✓" warna="yellow" /><DashboardCard judul="Total Absensi" nilai={data.absensi} keterangan="Seluruh data kehadiran" ikon="▤" warna="cream" /><DashboardCard judul="Program Studi" nilai={data.prodi} keterangan="Program studi terdaftar" ikon="⌘" warna="green" /></section><section className="mt-7 rounded-2xl bg-white p-6 shadow-soft"><h2 className="text-lg font-bold text-stone-900">Mulai dari sini</h2><p className="mt-1 text-sm text-stone-500">Pilih aktivitas yang ingin Anda lakukan hari ini.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><a href="/data-mahasiswa/tambah" className="rounded-xl bg-orange-50 p-4 transition hover:bg-orange-100"><b className="text-orange-800">+ Tambah Mahasiswa</b><span className="mt-1 block text-sm text-orange-700">Daftarkan mahasiswa dan buat QR Code.</span></a><a href="/scan-absensi" className="rounded-xl bg-sunshine-100 p-4 transition hover:bg-sunshine-300"><b className="text-orange-800">▣ Scan Absensi</b><span className="mt-1 block text-sm text-orange-700">Catat kehadiran dengan kamera.</span></a></div></section></>}</>;
}
